---
# tasks file for setup-apache-role
 - name: installing httpd
   yum:
     name: httpd
     state: installed
   when: ansible_os_family == "RedHat"
   notify: started httpd

 - name: installing apache2
   apt:
     name: apache2
     state: present
   when: ansible_os_family == "Debian"
   notify: started apache2

 - name: copy file
   copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html
      mode: 0777

