---
# handlers file for setup-apache-role
  - name: started httpd
    service:
        name: httpd
        state: started
    when: ansible_os_family == "RedHat"

  - name: started apache2
    service:
        name: apache2
        state: started
    when: ansible_os_family == "Debian"
      


